# Generated by Django 5.1 on 2024-08-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_music_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="user",
        ),
    ]
