# Generated by Django 5.1 on 2024-08-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_remove_music_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="music",
            name="music",
            field=models.FileField(help_text="Музыка", upload_to="music/%Y/%m/%d/"),
        ),
    ]
